version: "3.9"
services:
  queue_visualizate_streamlit:
    build:
      context: .
      dockerfile: dockerfile_data_view
    ports:
      - "8501:8501"
    entrypoint: ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
    volumes:
      - type: bind
        source: ./src
        target: /app
  queue_visualizate_data_ingest:
    build:
      context: .
      dockerfile: dockerfile_data_ingest
    entrypoint: ["python", "scheduled_jobs.py"]
    volumes:
      - ./src/:/app